"""Workout Classes

Revision ID: 1871bb7c3b0f
Revises: 92db23dd5a24
Create Date: 2024-08-10 15:44:35.410546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1871bb7c3b0f'
down_revision = '92db23dd5a24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_name', sa.String(), nullable=True),
    sa.Column('studio_location', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('class_duration', sa.Integer(), nullable=True),
    sa.Column('class_date', sa.DateTime(), nullable=True),
    sa.Column('class_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_classes')
    # ### end Alembic commands ###
