"""Workout Class

Revision ID: 411664f515d0
Revises: 1871bb7c3b0f
Create Date: 2024-08-10 16:01:14.810253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '411664f515d0'
down_revision = '1871bb7c3b0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('studio_name', sa.VARCHAR(), nullable=True),
    sa.Column('studio_location', sa.VARCHAR(), nullable=True),
    sa.Column('class_name', sa.VARCHAR(), nullable=True),
    sa.Column('class_duration', sa.INTEGER(), nullable=True),
    sa.Column('class_date', sa.DATETIME(), nullable=True),
    sa.Column('class_time', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
