"""update workoutclass model

Revision ID: 433afce78435
Revises: 3d0283da5922
Create Date: 2024-08-15 06:44:42.781258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '433afce78435'
down_revision = '3d0283da5922'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workoutclasses', sa.Column('user_claimed_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_workoutclasses_user_claimed_id_users'), 'workoutclasses', 'users', ['user_claimed_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_workoutclasses_user_claimed_id_users'), 'workoutclasses', type_='foreignkey')
    op.drop_column('workoutclasses', 'user_claimed_id')
    # ### end Alembic commands ###
