"""update db format

Revision ID: 49e92dfd6287
Revises: 865f6bc18f88
Create Date: 2024-08-11 13:31:00.788366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49e92dfd6287'
down_revision = '865f6bc18f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_class', schema=None) as batch_op:
        batch_op.alter_column('studio_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('studio_location',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('class_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('class_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('class_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('class_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_class', schema=None) as batch_op:
        batch_op.alter_column('class_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('class_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('class_duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('class_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('studio_location',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('studio_name',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
