"""Fix review model

Revision ID: 4b737b09affb
Revises: f9bb10200a7b
Create Date: 2024-09-02 17:52:52.491229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b737b09affb'
down_revision = 'f9bb10200a7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review', sa.String(), nullable=False))
    op.drop_column('reviews', 'rating')
    op.drop_column('reviews', 'content')
    op.drop_column('reviews', 'created_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('reviews', sa.Column('content', sa.VARCHAR(), nullable=False))
    op.add_column('reviews', sa.Column('rating', sa.INTEGER(), nullable=False))
    op.drop_column('reviews', 'review')
    # ### end Alembic commands ###
