"""foeign key to models

Revision ID: 54db3471e978
Revises: ae8d4c20964d
Create Date: 2024-08-13 05:57:55.177423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54db3471e978'
down_revision = 'ae8d4c20964d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_user_id_users'), 'reviews', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_user_id_users'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'user_id')
    # ### end Alembic commands ###
