"""remove temp field

Revision ID: 606226d963db
Revises: bd9d873adfd9
Create Date: 2024-08-10 14:03:07.748949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606226d963db'
down_revision = 'bd9d873adfd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('available_classes')
    op.drop_table('claimed_classes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claimed_classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('available_class_id', sa.INTEGER(), nullable=True),
    sa.Column('claimed_time', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['available_class_id'], ['available_classes.id'], name='fk_claimed_classes_available_class_id_available_classes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_claimed_classes_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('available_classes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(), nullable=True),
    sa.Column('studio', sa.VARCHAR(), nullable=True),
    sa.Column('class_time', sa.DATETIME(), nullable=True),
    sa.Column('class_duration', sa.INTEGER(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_available_classes_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('last_name', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('temp_field', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
