"""Reviews

Revision ID: 865f6bc18f88
Revises: 411664f515d0
Create Date: 2024-08-11 09:35:07.020403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '865f6bc18f88'
down_revision = '411664f515d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
