"""Only User

Revision ID: 92db23dd5a24
Revises: aee03da8f746
Create Date: 2024-08-10 14:41:07.987899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92db23dd5a24'
down_revision = 'aee03da8f746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
