"""migrate

Revision ID: acc126c77a63
Revises: 49e92dfd6287
Create Date: 2024-08-11 14:07:20.879629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acc126c77a63'
down_revision = '49e92dfd6287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_name', sa.String(), nullable=True),
    sa.Column('studio_location', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('class_duration', sa.Integer(), nullable=True),
    sa.Column('class_date', sa.DateTime(), nullable=True),
    sa.Column('class_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('review')
    op.drop_table('workout_class')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_class',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('studio_name', sa.VARCHAR(), nullable=False),
    sa.Column('studio_location', sa.VARCHAR(), nullable=False),
    sa.Column('class_name', sa.VARCHAR(), nullable=False),
    sa.Column('class_duration', sa.INTEGER(), nullable=False),
    sa.Column('class_date', sa.DATE(), nullable=False),
    sa.Column('class_time', sa.TIME(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('review', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('workout_classes')
    # ### end Alembic commands ###
