"""empty message

Revision ID: b99fc7620ddc
Revises: 
Create Date: 2024-08-18 17:52:59.451408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99fc7620ddc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('workoutclasses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('studio_name', sa.String(), nullable=True),
    sa.Column('studio_location', sa.String(), nullable=True),
    sa.Column('class_name', sa.String(), nullable=True),
    sa.Column('class_duration', sa.Integer(), nullable=True),
    sa.Column('class_date', sa.String(), nullable=True),
    sa.Column('class_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_claimed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_claimed_id'], ['users.id'], name=op.f('fk_workoutclasses_user_claimed_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workout_class_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reviews_user_id_users')),
    sa.ForeignKeyConstraint(['workout_class_id'], ['workoutclasses.id'], name=op.f('fk_reviews_workout_class_id_workoutclasses')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('workoutclasses')
    op.drop_table('users')
    # ### end Alembic commands ###
